---
name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    permissions:
      checks: write
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - run: npm ci

      - run: mkdir -p mocha

      - name: Run tests
        run: npm test -- --reporter json --reporter-option output=mocha/${{ matrix.os }}.json

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: test results (${{ matrix.os }})
          path: mocha/${{ matrix.os }}.json
          reporter: mocha-json
